name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker images
      run: docker-compose -f docker-compose-build.yaml build --parallel

    - name: Tagging Docker images
      run: |
        docker tag udagram-api-feed caonhat91/udagram-api-feed:latest
        docker tag udagram-api-user caonhat91/udagram-api-user:latest
        docker tag reverseproxy caonhat91/reverseproxy:latest
        docker tag udagram-frontend:local caonhat91/udagram-frontend:latest

    - name: Push Docker images
      run: docker-compose -f docker-compose-build.yaml push

