name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose-build.yaml build --parallel
        docker-compose -f docker-compose-build.yaml push
      with:
        tags: |
          caonhat91/udagram-api-feed:latest
          caonhat91/udagram-api-user:latest
          caonhat91/udagram-frontend:latest
          caonhat91/reverseproxy:latest
